[package]
name = "geometroid"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.33"
ash-window = "0.7"
winit = "0.25"
glam = "0.20.1"
log = "0.4"
env_logger = "0.9"
memoffset = "0.6.5"
